### ISSUE TITLE
Custom code getting cut off

### ISSUE THREAD

**Issue by mshafer-NI** [mshafer1/AHK-generator#1]
http://ahkgen.com/?length=1&func5=KEY&skey5%5B%5D=CTRL&skey5%5B%5D=SHIFT&skeyValue5=g&Code5=Send%2C+%5Ec%0D%0ASleep+50%0D%0ARun%2C+http%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3D%25clipboard%25%0D%0Areturn&option5=Custom

Should yield, 
^+g::Send, ^c
Sleep 50
Sleep 50
Run, http://www.google.com/search?q=%clipboard%
return

is yielding:
^+g::Send, ^c
Sleep 50
Run, http://www.google.com/search?q

**Comment by mshafer1** [comment]
Fixed
