### ISSUE TITLE
Append Edit-Shortcut

### ISSUE THREAD

**Issue by ptar** [mshafer1/AHK-generator#14]
Please automatically insert a hotkey to edit the generated script.

Example on Ctrl-Win-#
```
;Edit
^##::ActivateOrOpenChrome("editscript", "https://www.ahkgen.com/?length=2&comment0=Just+a+Hotstring&func0=STRING&skeyValue0=just&input0=Just+a+Hotstring&option0=Replace&comment1=Regards&func1=STRING&skeyValue1=br&input1=Best+regards&option1=Replace")
```

This way, it would be easy to edit your own generated script at any time.

Alternatively: Add a function which generates the Edit-URL based on the contents of the local script.

**Comment by mshafer1** [comment]
So,

If I automatically insert a hotkey, that will be reserving that key permanently.

If on the other hand, I put the page url in a comment, it could be opened up either by copy and pasting, or (depending on the text editor you use) clicking on the link.

Option 2 would be to store it in a variable (something like ```%edit_url%```). This would allow the user to assign their own hotkey to open the url.

Thoughts?

**Comment by ptar** [comment]
You're right about the problem with the permanent reservation, which would not be good.
How about adding the call of the script URL to the selectable functions and show it as a second default line (after the empty one) if it's not called via a script URL (=initial call). You might preset a default hotkey which can easily be changed if needed.

**Comment by mshafer1** [comment]
I invited you as a collaborator so I can put you on the pull request for this as a reviewer.

**Comment by ptar** [comment]
That's ok for me!

**Comment by mshafer1** [comment]
Pushed live 10/4/2018

**Comment by mshafer1** [comment]
Ok
